sudo: required
services:
  - docker
before_install:
  - docker build -t nadavribak/docker-testings -f Dockerfile.dev .
script:
  - docker run nadavribak/docker-testings npm run test -- --watchAll=false
