sudo: required
services:
  - docker
before_install:
  - docker build -t nadavribak/docker-testings -f Dockerfile.dev .
after_deploy:
  - echo "done deploying"
script:
  - docker run nadavribak/docker-testings npm run test -- --watchAll=false
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-testings"
  env: "react-testings-env"
  bucket_name: "elasticbeanstalk-us-east-1-914632565753"
  bucket_path: "react-testings"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"

